# Whenever a push is made to the master branch then run the job
on: 
  push:
    branches:
      - development
env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: Bin
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  # job id, can be anything
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --export "HTML5" build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: dev
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
      - name: upload web artifact
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/web/web.zip
          asset_name: web.zip
          asset_content_type: application/zip