# Whenever a push is made to the master branch then run the job
on: 
  #workflow_dispatch:
    #inputs:
      #tag: latest
  push:
    branches:
      - development
env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: Bin
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-web:
    name: Web Export
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --export "HTML5" build/web/index.html
          cd build/web
          zip -r $GITHUB_WORKSPACE/build/web/web.zip ./*
          cd ..
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web/web.zip
  release:
    needs: [build-web]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: web
          path: web
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-dev-release
          files: /home/runner/work/faefolk/faefolk/web/*
      - name: Triggering IC Deployment
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'CHANGELOG.md'
        destination_repo: 'ICCards/faefolk_web/tree/development'
        destination_folder: './'
        user_email: 'dev.jonathan.green@gmail.com'
        user_name: 'ALLiDoizCode'
        commit_message: 'A custom message for the commit'