# Whenever a push is made to the master branch then run the job
on: 
  #workflow_dispatch:
    #inputs:
      #tag: latest
  push:
    branches:
      - development
env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: Bin
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  # job id, can be anything
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --export "HTML5" build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web
      - name: Creating release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/web/web.zip"
          bodyFile: "CHANGELOG.md"
          tag: development
          token: ${{ secrets.GITHUB_TOKEN }}