# Whenever a push is made to the master branch then run the job
on: 
  push:
    branches:
      - development
env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: Bin

jobs:
  # job id, can be anything
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          godot --export "HTML5" web.zip
          mv web.zip build/web
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web